name: Feature request
description: Suggest an improvement to Rowla.
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: Describe the task that you want Rowla to help you complete.
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed behavior
    validations:
      required: true
  - type: textarea
    id: workaround
    attributes:
      label: Current workaround
      description: How do you complete this task now? What causes the difficulty?
